import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import EditInfo from "../components/EditInfo";
import Loading from "../components/Loading";
import LoggedIn from "../components/LoggedIn";
import Navbar from "../components/Navbar";
import PersonalInfo, { User } from "../components/PersonalInfo";
import { getProfile } from "../utils/apiCalls";

const Home: NextPage = () => {
  const [edit, setEdit] = useState<boolean>(false);
  const [user, setUser] = useState<User>();
  const [update, setUpdate] = useState<boolean>(false);

  useEffect(() => {
    console.log("update, fetch");
    getProfile().then((res) => {
      if (typeof res === "object") setUser(res);
    });
  }, [update]);
  return (
    <div className="container mx-auto  h-screen">
      <Head>
        <title>Create Next App With TW + TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoggedIn
        fallbackUrl="/auth/login"
        isLoggedIn={true}
        LoadingComponent={<Loading />}
      >
        <Navbar user={user} />
        {edit ? (
          <EditInfo
            update={update}
            setUpdate={setUpdate}
            setEdit={setEdit}
            user={user}
          />
        ) : (
          <PersonalInfo setEdit={setEdit} user={user} />
        )}
      </LoggedIn>
    </div>
  );
};

export default Home;
